version: '3.1'

services:

  mongo:
    container_name: mongo
    build:
      context: ./mongo
    image: mongo:latest
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: 123456
      MONGO_INITDB_DATABASE: CWA
    volumes:
      - ./mongo_data:/data
      - ./mongo_seed:/mongo_seed
    ports:
      - 27017:27017
